spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    stream:
      kafka:
        binder:
          noOfPartitions: 1
          replicationFactor: 1
      function:
        definition: productEventProducer
      bindings:
        productEventProducer-out-0: #a producer
          destination: product-event-topic
